### ISSUE TITLE
flutter_local_auth_invisible v2.1 v2.2 on androidX does not working

### ISSUE THREAD

**Issue by kiaxseventh** [priezz/flutter_local_auth_invisible#21]
hello dear
new version example does not working on finger print auth

i tried on flutter 2.5.2  2.5.3 stable version
i tried flutter_local_auth_invisible v2.1 v2.2

log error
```
Unhandled Exception: PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null, null)
E/flutter (25182): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (25182): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (25182): <asynchronous suspension>
E/flutter (25182): #2      LocalAuthentication.authenticate (package:flutter_local_auth_invisible/flutter_local_auth_invisible.dart:128:13)
E/flutter (25182): <asynchronous suspension>
E/flutter (25182): #3      AuthProviderState.build.<anonymous closure> (package:local_auth_invisible_example/main.dart:123:15)
E/flutter (25182): <asynchronous suspension>
```

**Comment by priezz** [comment]
You need to use FragmentActivity to let it work. I will add it in the README. Look [here](https://pub.dev/packages/local_auth#android-integration) for the details.
